# Generated by Django 5.0.6 on 2024-05-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_recipeequipment_recipe_dish_equip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipeequipment'),
        ),
        migrations.CreateModel(
            name='VirtualOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dishes', models.ManyToManyField(to='app.dish')),
            ],
        ),
    ]
