# Generated by Django 5.0.6 on 2024-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dish_equip_virtualorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualorder',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='virtualorder',
            name='name',
        ),
        migrations.AddField(
            model_name='virtualorder',
            name='selected_dishes',
            field=models.ManyToManyField(related_name='virtualorders', to='app.dish'),
        ),
        migrations.AddField(
            model_name='virtualorder',
            name='selected_quantities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
