# Generated by Django 5.0.6 on 2024-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_virtualorder_dishes_remove_virtualorder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualorder',
            name='selected_quantities',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='virtualorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
