# Generated by Django 5.0.6 on 2024-05-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_virtualorder_selected_quantities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, null=True),
        ),
    ]
