# Generated by Django 5.0.6 on 2024-05-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_virtualorder_virtualorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualOrderSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_quantities', models.IntegerField(blank=True, default=1, null=True)),
                ('total_cost', models.DecimalField(decimal_places=3, default=1, max_digits=10, null=True)),
                ('selected_dishes', models.ManyToManyField(related_name='virtualorders', to='app.dish')),
            ],
        ),
        migrations.DeleteModel(
            name='VirtualOrders',
        ),
    ]
