# Generated by Django 5.0.6 on 2024-05-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_virtualordersec_delete_virtualorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualordersec',
            name='selected_dishes',
            field=models.ManyToManyField(related_name='virtualordersec', to='app.dish'),
        ),
    ]
