# Generated by Django 5.0.6 on 2024-05-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_virtualordersec_selected_quantities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualordersec',
            name='selected_dishes',
        ),
        migrations.RemoveField(
            model_name='virtualordersec',
            name='selected_quantities',
        ),
        migrations.CreateModel(
            name='SelectedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dish')),
                ('virtual_order_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_dishes', to='app.virtualordersec')),
            ],
        ),
    ]
