# Generated by Django 5.0.6 on 2024-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_virtualordersec_selected_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteddish',
            name='virtual_order_sec',
        ),
        migrations.AddField(
            model_name='selecteddish',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selecteddish',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='selecteddish',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VirtualOrderSec',
        ),
    ]
