# Generated by Django 5.0.6 on 2024-05-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_selecteddish_virtual_order_sec_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedDish',
        ),
    ]
