# Generated by Django 5.0.6 on 2024-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected',
            name='num_persons',
            field=models.IntegerField(default=1),
        ),
    ]
