# Generated by Django 5.0.6 on 2024-05-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_selected_num_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
